In [1]:
S = 100 #Initial Stock Price
T = 1 #lets say T denotes the End Period when we we calculate the Payoff from the option
r = 0.02 #it denotes the interest rate 
sigma = 0.4 #it denotes the volatility of the stock
Nsimulations = 10000 # how many numbers we want to simulate
Nsteps = 200 #it denotes the no of periods(like dayes or months) within T 
K = 105 #here it is the strike price

In [8]:
dt = T/Nsteps

In [9]:
drift = (r-0.5*(sigma**2))*dt #drift term

In [10]:
import numpy as np
a = sigma*np.sqrt(dt) #time component

In [11]:
x = np.random.normal(0,1,(Nsimulations,Nsteps)) #random variable , here we define this as matrix of Nsimulations*Nsteps
x

array([[ 1.33647837,  0.59091327, -0.60238471, ...,  0.60556629,
        -1.4695292 ,  1.28137144],
       [ 0.45204877, -0.27358544,  0.16412229, ..., -0.88244918,
         0.76870614,  0.60809065],
       [ 0.47661652,  1.33203827, -1.92777459, ...,  0.15402122,
        -0.37047834, -1.25331533],
       ...,
       [-0.24697848, -2.20893713, -0.95534491, ..., -1.83788736,
         0.74030361, -1.09322099],
       [ 0.00507335, -0.90460705, -1.39850463, ...,  0.25858823,
         0.30897309, -0.73623682],
       [ 0.58402171,  0.24618228,  0.65992046, ...,  0.04690493,
        -0.60161455,  0.11701465]])

In [12]:
Smat = np.zeros((Nsimulations,Nsteps)) #here we are denoting the matrix of stock price, we initialized the matrix with Zeros
Smat

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Smat matrix -  the column defines the no of Steps , here Nsteps =4, and the row defines the no of Simulations, here Nsimulations = 5
                          

In [13]:
Smat[:,0] = Smat[:,0] + S #at T= 0 we are saying that the stock price is 100. So our the 1st column of our Smat matrix should be 100
Smat 

array([[100.,   0.,   0., ...,   0.,   0.,   0.],
       [100.,   0.,   0., ...,   0.,   0.,   0.],
       [100.,   0.,   0., ...,   0.,   0.,   0.],
       ...,
       [100.,   0.,   0., ...,   0.,   0.,   0.],
       [100.,   0.,   0., ...,   0.,   0.,   0.],
       [100.,   0.,   0., ...,   0.,   0.,   0.]])

# In the 2nd time period , which is T=1 we have to use the Geometric Brownian Motion formula in order to get the different values for n number of  simulations , here we are taking Nsimulations = 10000

In [14]:
for i in range(1,Nsteps):
    Smat[:,i] = Smat[:,i] + Smat[:,i-1]*np.exp(drift + a*x[:,i])
Smat

array([[100.        , 101.65489937,  99.90759659, ..., 130.99971572,
        125.62868235, 130.2262403 ],
       [100.        ,  99.19940548,  99.63107366, ...,  85.29836232,
         87.14710459,  88.63235302],
       [100.        , 103.80829884,  98.27014013, ..., 188.93687335,
        186.91131369, 180.34742606],
       ...,
       [100.        ,  93.9151776 ,  91.38403344, ...,  40.61801648,
         41.46504038,  40.19046236],
       [100.        ,  97.44460227,  93.63725713, ...,  98.92488835,
         99.76325583,  97.67796689],
       [100.        , 100.66853341, 102.5344297 , ..., 127.25418966,
        125.06959599, 125.44658172]])

# Here We can see at T=1 the 5 different values(the last column) of Stock, where few values are more than 100 and few are below 100

# Now we have to calculate the Call Payoff at time T = 1 means we have to take the last column value of Smat and check with the strike Price

In [15]:
q = Smat[:,-1]-K #here q denotes the call payoff

# The payoff of Asian Call option is the maximum between average stock price 

In [16]:
asian_q = np.mean(Smat,axis=1) - K

# The Call payoffs are mentioned below

In [17]:
q

array([ 25.2262403 , -16.36764698,  75.34742606, ..., -64.80953764,
        -7.32203311,  20.44658172])

# The Asian Call payoffs are mentioned below

In [18]:
asian_q

array([  3.50017617,   1.78911621,  35.1085554 , ..., -27.91966592,
         4.32938143,  19.28032074])

# Now for call Pricing, Call payoff per share = (MAX (stock price - strike price, 0) - premium per share) 

In [19]:
for i in range (len(q)):
    if q[i]<0 :
        q[i]=0
    else :
        q[i] = q[i]

# Now lets check the call Payoff which is denoted by q here

In [20]:
q

array([25.2262403 ,  0.        , 75.34742606, ...,  0.        ,
        0.        , 20.44658172])

# Lets do it for Asian call

In [21]:
for i in range (len(asian_q)):
    if asian_q[i]<0 :
        asian_q[i]=0
    else :
        asian_q[i] = asian_q[i]
asian_q

array([ 3.50017617,  1.78911621, 35.1085554 , ...,  0.        ,
        4.32938143, 19.28032074])

# For Put Pricing, Put payoff per share = (MAX (strike price - stock price, 0) - premium per share)

In [22]:
p = K - Smat[:,-1] #here q denotes the put payoff
for i in range (len(p)):
    if p[i]<0 :
        p[i]=0
    else :
        p[i] = p[i]

# Now lets check the put Payoff which is denoted by p here

In [23]:
p

array([ 0.        , 16.36764698,  0.        , ..., 64.80953764,
        7.32203311,  0.        ])

# Payoff of Call and Put will be the respective mean() of Call(here q) and               Put(here P)

In [24]:
payoff_call = np.mean(q)
payoff_put = np.mean(p)

In [25]:
payoff_call

14.828388095187012

In [26]:
payoff_put

17.817565776749948

# Lets calculate payoff for Asian Call

In [27]:
payoff_asiancall = np.mean(asian_q)
payoff_asiancall

7.5700400355669615

# Now we have to calculate the call price and Put price at time time = 0. Hence we have to discount the Call and Put payoffs respectively

In [28]:
call= payoff_call*np.exp(-r*T)
put = payoff_put*np.exp(-r*T)

In [29]:
call

14.534766338179994

In [30]:
put

17.464754335926145

# Let's calcuallate the Asian Call price

In [32]:
asian_call_price = payoff_asiancall*np.exp(-r*T)
asian_call_price

7.420143199741758

# Here the values of Call and put , we get by doing only 5 simulations. We need to do this for 10000 simulations - S = 100, 𝑟𝑓 = 0.02, 𝜎 = 0.4, 𝑇 = 1 𝑦𝑒𝑎𝑟, 𝑀 = 200